import XCTest
@testable import PencilCore

final class ClipboardStoreSupportTests: XCTestCase {
    // MARK: Privacy

    func testPasswordManagerAndMarkerTypesAreIgnored() {
        XCTAssertTrue(ClipboardPrivacy.shouldIgnore(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
        XCTAssertTrue(ClipboardPrivacy.shouldIgnore(types: ["org.nspasteboard.TransientType"]))
        XCTAssertTrue(ClipboardPrivacy.shouldIgnore(types: ["org.nspasteboard.AutoGeneratedType"]))
        XCTAssertTrue(ClipboardPrivacy.shouldIgnore(types: ["public.utf8-plain-text", "com.agilebits.onepassword"]))
        XCTAssertTrue(ClipboardPrivacy.shouldIgnore(types: ["com.agilebits.onepassword.secure"]))
    }

    func testOrdinaryContentIsRecorded() {
        XCTAssertFalse(ClipboardPrivacy.shouldIgnore(types: ["public.utf8-plain-text", "public.rtf"]))
        XCTAssertFalse(ClipboardPrivacy.shouldIgnore(types: ["public.file-url", "public.png", "public.tiff"]))
        XCTAssertFalse(ClipboardPrivacy.shouldIgnore(types: []))
    }

    // MARK: Classification

    func testFilesWin() {
        XCTAssertEqual(ClipboardClassifier.kind(hasFileURLs: true, hasImage: true, plainText: "/Users/x/a.png"), .file)
    }

    func testImageWithoutRealTextIsImage() {
        XCTAssertEqual(ClipboardClassifier.kind(hasFileURLs: false, hasImage: true, plainText: nil), .image)
        XCTAssertEqual(ClipboardClassifier.kind(hasFileURLs: false, hasImage: true, plainText: "  "), .image)
        XCTAssertEqual(ClipboardClassifier.kind(hasFileURLs: false, hasImage: true,
                                                plainText: "https://example.com/cat.png"), .image)
    }

    func testTextWithPictureRenditionIsText() {
        // Office/Pages/Numbers put a picture of the selection next to the text.
        XCTAssertEqual(ClipboardClassifier.kind(hasFileURLs: false, hasImage: true, plainText: "Q3 revenue\t42"), .text)
    }

    func testPlainTextAndEmpty() {
        XCTAssertEqual(ClipboardClassifier.kind(hasFileURLs: false, hasImage: false, plainText: "hi"), .text)
        XCTAssertNil(ClipboardClassifier.kind(hasFileURLs: false, hasImage: false, plainText: " \n "))
        XCTAssertNil(ClipboardClassifier.kind(hasFileURLs: false, hasImage: false, plainText: nil))
    }

    func testFileFingerprintIsOrderSensitivePathList() {
        XCTAssertEqual(ClipboardFingerprint.files(["/a", "/b"]), ClipboardFingerprint.files(["/a", "/b"]))
        XCTAssertNotEqual(ClipboardFingerprint.files(["/a", "/b"]), ClipboardFingerprint.files(["/b", "/a"]))
    }

    // MARK: Formatting

    func testRelativeTimes() {
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = TimeZone(identifier: "UTC")!
        let now = ISO8601DateFormatter().date(from: "2027-03-10T15:00:00Z")!
        func rel(_ secondsAgo: TimeInterval) -> String {
            ClipboardFormat.relative(now.addingTimeInterval(-secondsAgo), now: now, calendar: cal)
        }
        XCTAssertEqual(rel(5), "Just now")
        XCTAssertEqual(rel(-30), "Just now", "clock skew never shows the future")
        XCTAssertEqual(rel(5 * 60), "5m ago")
        XCTAssertEqual(rel(3 * 3600), "3h ago")
        XCTAssertEqual(rel(20 * 3600), "Yesterday") // 19:00 the day before
        XCTAssertEqual(rel(3 * 86400), "3d ago")
        XCTAssertEqual(rel(30 * 86400), "Feb 8")
        XCTAssertEqual(rel(400 * 86400), "Feb 3, 2026")
    }

    func testSubtitle() {
        let now = Date(timeIntervalSince1970: 1_800_000_000)
        let img = ClipboardItem(kind: .image, fingerprint: "i", copiedAt: now, pixelWidth: 800, pixelHeight: 600)
        XCTAssertEqual(ClipboardFormat.subtitle(for: img, now: now), "Just now · 800×600")
        let text = ClipboardItem(kind: .text, fingerprint: "t", copiedAt: now.addingTimeInterval(-120), text: "hey")
        XCTAssertEqual(ClipboardFormat.subtitle(for: text, now: now), "2m ago · 3 chars")
        let file = ClipboardItem(kind: .file, fingerprint: "f", copiedAt: now, filePaths: ["/a.mov"],
                                 fileTypeName: "MPEG-4 movie")
        XCTAssertEqual(ClipboardFormat.subtitle(for: file, now: now), "Just now · MPEG-4 movie")
    }
}

final class ClipboardStoreCaptureShapeTests: XCTestCase {
    /// A Pencil capture puts a file URL plus PNG (and no text) on the pasteboard:
    /// it's one file item, identified by its path, so copying it again dedupes.
    func testPencilCaptureWithoutTextIsOneFileItem() {
        XCTAssertEqual(ClipboardClassifier.kind(hasFileURLs: true, hasImage: true, plainText: nil), .file)
        let path = "/Users/me/Pictures/Pencil/pencil-20270101-120000.png"
        var s = ClipboardStore()
        let a = ClipboardItem(id: "a", kind: .file, fingerprint: ClipboardFingerprint.files([path]),
                              copiedAt: Date(timeIntervalSince1970: 1), pixelWidth: 10, pixelHeight: 10, filePaths: [path])
        var b = a
        b.id = "b"
        b.copiedAt = Date(timeIntervalSince1970: 2)
        _ = s.add(a)
        XCTAssertEqual(s.add(b), .promoted(existingID: "a"))
        XCTAssertEqual(s.count, 1)
    }
}

final class ClipboardTextMetaTests: XCTestCase {
    func testTextPreviewMetaLine() {
        let now = Date(timeIntervalSince1970: 1_800_000_000)
        XCTAssertEqual(ClipboardFormat.textMeta(copiedAt: now.addingTimeInterval(-120), characters: 84, now: now),
                       "Copied 2m ago · 84 characters")
        XCTAssertEqual(ClipboardFormat.textMeta(copiedAt: now, characters: 1, now: now), "Copied just now · 1 character")
    }

    func testTextRowSubtitleIsMetaOnly() {
        let now = Date(timeIntervalSince1970: 1_800_000_000)
        let text = "It reached me as an image, which means the fix is working"
        let item = ClipboardItem(kind: .text, fingerprint: "t", copiedAt: now, text: text)
        let subtitle = ClipboardFormat.subtitle(for: item, now: now)
        XCTAssertFalse(subtitle.contains("reached"), "the row's subtitle never repeats the text")
        XCTAssertEqual(subtitle, "Just now · \(text.count) chars")
    }
}
