import Foundation

/// Which pasteboard contents must never be saved.
public enum ClipboardPrivacy {
    /// nspasteboard.org markers that password managers and other apps set on secrets and
    /// on content that isn't really the user's copy.
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    /// Type prefixes that mark a password manager's copy (1Password uses several).
    public static let ignoredTypePrefixes = ["com.agilebits."]

    public static func shouldIgnore(types: [String]) -> Bool {
        types.contains { t in
            ignoredTypes.contains(t) || ignoredTypePrefixes.contains { t.hasPrefix($0) }
        }
    }
}

/// Decides what a pasteboard holds, from what it carries.
public enum ClipboardClassifier {
    /// - file URLs win (Finder copies, Pencil snapshots which also carry the PNG);
    /// - image data wins over text when the text is missing, blank, or just a one-line
    ///   URL/path (browsers put the image address next to a copied image);
    /// - otherwise text, when there is any (rich text from Office/Pages also carries a
    ///   picture rendition, which is not what the user copied);
    /// - otherwise nothing worth saving.
    public static func kind(hasFileURLs: Bool, hasImage: Bool, plainText: String?) -> ClipboardItem.Kind? {
        if hasFileURLs { return .file }
        let trimmed = plainText?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        if hasImage {
            if trimmed.isEmpty || looksLikeLocator(trimmed) { return .image }
            return .text
        }
        return trimmed.isEmpty ? nil : .text
    }

    static func looksLikeLocator(_ s: String) -> Bool {
        guard !s.contains(where: \.isNewline), !s.contains(" ") else { return false }
        return s.hasPrefix("http://") || s.hasPrefix("https://") || s.hasPrefix("file://") || s.hasPrefix("/")
    }
}

public enum ClipboardFingerprint {
    /// Files are the same copy when they're the same paths in the same order.
    public static func files(_ paths: [String]) -> String {
        "files:" + paths.joined(separator: "\n")
    }
}

public enum ClipboardFormat {
    /// "Just now", "5m ago", "3h ago", "Yesterday", "4d ago", then a short date.
    public static func relative(_ date: Date, now: Date = Date(), calendar: Calendar = .current) -> String {
        let s = max(0, now.timeIntervalSince(date))
        if s < 45 { return "Just now" }
        if s < 3600 { return "\(max(1, Int((s / 60).rounded())))m ago" }
        if calendar.isDate(date, inSameDayAs: now) { return "\(Int(s / 3600))h ago" }
        if let y = calendar.date(byAdding: .day, value: -1, to: now), calendar.isDate(date, inSameDayAs: y) {
            return "Yesterday"
        }
        let days = calendar.dateComponents([.day], from: calendar.startOfDay(for: date),
                                           to: calendar.startOfDay(for: now)).day ?? 0
        if days < 7 { return "\(days)d ago" }
        let f = DateFormatter()
        f.calendar = calendar
        f.timeZone = calendar.timeZone
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = calendar.isDate(date, equalTo: now, toGranularity: .year) ? "MMM d" : "MMM d, yyyy"
        return f.string(from: date)
    }

    /// "12 KB", "3.4 MB".
    public static func bytes(_ n: Int64) -> String {
        ByteCountFormatter.string(fromByteCount: n, countStyle: .file)
    }

    /// The meta line under a text preview: "Copied 2m ago · 84 characters".
    /// `characters` is the full text's length (long text keeps only a prefix inline).
    public static func textMeta(copiedAt: Date, characters n: Int, now: Date = Date()) -> String {
        let when = relative(copiedAt, now: now)
        let lowered = when.prefix(1).lowercased() + when.dropFirst()
        return "Copied \(lowered) · \(n) character\(n == 1 ? "" : "s")"
    }

    /// The row subtitle: time, then type/size details.
    public static func subtitle(for item: ClipboardItem, now: Date = Date()) -> String {
        var parts = [relative(item.copiedAt, now: now)]
        switch item.kind {
        case .text:
            let n = (item.text ?? "").count
            parts.append(item.fullTextFile != nil ? "long text" : "\(n) char\(n == 1 ? "" : "s")")
        case .image:
            if let w = item.pixelWidth, let h = item.pixelHeight { parts.append("\(w)×\(h)") }
            if let size = item.fileSize { parts.append(bytes(size)) }
        case .file:
            if item.filePaths.count > 1 { parts.append("\(item.filePaths.count) files") }
            if let type = item.fileTypeName { parts.append(type) }
            if let size = item.fileSize { parts.append(bytes(size)) }
        }
        return parts.joined(separator: " · ")
    }
}
